version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  webserver:
    image: apache/airflow:2.7.1-python3.10
    command: webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Set the path to google credentials
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/google_credentials.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./google_credentials.json:/opt/airflow/google_credentials.json
    depends_on:
      - postgres

  scheduler:
    image: apache/airflow:2.7.1-python3.10
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/google_credentials.json
      - _PIP_ADDITIONAL_REQUIREMENTS=yfinance pandas
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./google_credentials.json:/opt/airflow/google_credentials.json
    depends_on:
      - postgres